<?php
            require_once('stripe/init.php');

			// Set Stripe API Key
			\Stripe\Stripe::setApiKey("sk_test_t2dbnO7tLqxiz3MeyAIsLjJQ");
			\Stripe\Stripe::setApiVersion("2015-08-07");

            $token_id = $_POST['stripeToken']; // It is generated by client side code
			$customer = \Stripe\Customer::create(array(
			"source" => $token_id, // obtained with Stripe.js
			"description" => 'description for customer'
			));

			$customer_id=$customer->id;
			// Create a charge object to charge a credit or a debit card
			$charge = \Stripe\Charge::create(array(
			'customer'		=>	$customer_id,
			'amount'		=>	100,
			'currency'		=>	"usd",
			"description"	=>	'description for customer'
			));
	   

 ?>